Repository ISISComputingGroup/EPICS-kepco, pull requests merged in 2020-11, with the labels that each got.

#7 Ticket3185 remote mode reliability
  kepcoApp/Db/kepco.db
  kepcoApp/protocol/kepco.proto
Labels: size/L

#8 Ticket 5661: Added PVs for ramping KEPCO
  kepcoApp/Db/Makefile
  kepcoApp/Db/kepco.db
  kepcoApp/Db/kepco_ramping.db
Labels: size/L

#10 Final EOL
  kepcoApp/Db/kepco_ramping.db
Labels: size/XS

#11 Autosave correct value
  kepcoApp/Db/kepco.db
  kepcoApp/Db/kepco_ramping.db
Labels: size/XS

#9 Ticket 5662: Add ability to select calibration for field
  example_calibration/default_calib.dat
  example_calibration/field_double_amps.dat
  kepcoApp/Db/kepco.db
  kepcoApp/Db/kepco_ramping.db
Labels: size/S
